---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-minio",
         minio_server_addr: "{{ansible_default_ipv4.address}}",
         minio_server_opts: "",
         minio_user: minio,
         minio_access_key: "XCF1G7SEAZ1O04QM83WN",
         minio_secret_key: "7cloFo3jrfOdxTMTyBPNXlWK2EB6nd72YGBC0cTt"

       }

  tasks:

    - debug: msg="Tasks section"
